- README.md
> Added note to README about deleting postgres PVC if re-deploying CAST in previously used namespace. Fixed typos in parameters table.
> Added note about deleting PVC to README

- collector/collector.go
> Added more logging to the collector and made sure logging indicates that the pod is running successfully. Added postgres pings to make sure the database is ready before record export is attempted. 
> Deployed CAST and confirmed logging is more verbose and final log message for a running collector pod indicates it is running successfully.
> added more logging to collector

- README.md
> Fixed the links in the Install section to the Helm Parameters section. 
> Confirmed links worked locally.
> Fixed helm parameters links

- Makefile
- collector/collector.go
- collector/collector_test.go
- sql/sample-data/traffic.sql
> Added function to detect JWTs in requests, unit test for function, and test data to the sample data file. 
> Confirmed test data could be inserted into postgres. 
> Confirms function can detect JWTs in requests when the JWT is in the header and various parts of the body as well as JWTs with invalid signatures.
> Added function to detect JWTs in requests

- .github/workflows/linter.yml
- Makefile
- README.md
- collector/collector.go
- go.mod
- go.sum
- k8s/helm/cast/files/init.sql
- scripts/cast-ui-local-dev-server.sh
- skaffold.yaml
- sql/sample-data/traffic.sql
- ui/jest.config.js
- ui/src/__tests__/analysis/reused-authentication.test.ts
- ui/src/__tests__/findings.test.ts
- ui/src/lib/analysis/reused-authentication.ts
- ui/src/lib/findings.ts
- ui/src/pages/api/analyses.ts
- Implemented the analysis framework
- Ported the reused authentication analysis to the framework
- Implemented the `/api/analyses` endpoint that runs all analyses.
> Implementation of the findings framework

- README.md
Signed-off-by: Matthew Clive <max@corsha.com>
- Updated the README summary of CAST.
> Readme: tighten language

- sql/sample-data/traffic.sql
Fix broken sql script from merge
redeployed the dev postgres container and injected the test data.
na
> Fix SQL after findings update.

- k8s/helm/cast/files/init.sql
"Cast" is a psql keyword.  changed the "Cast" Column to meta as instructed.
Tested in dev stack to make sure meta is not a keyword.
NA
> Fix the init.db script

- ui/Dockerfile
- Removed docker command to copy now-nonexistent `.npmrc`, restoring the frontend Docker container build
```bash
cd ui
docker build -t cast:test.build .
```
> Bugfix: get frontend Docker build working

- .github/workflows/linter.yml
- ui/package-lock.json
- ui/package.json
> Updated CI so that tests run using the Lisbon timezone as a smoke test for incorrect handling of UTC dates from the backend.
> Confirmed tests worked locally with timezone set and in actions.
> CI UI use Lisbon/Europe timezones

- ui/components/app/Analysis/ExpiredJWTCard.spec.tsx
- ui/components/app/Analysis/ExpiredJWTCard.tsx
- ui/components/app/Analysis/__snapshots__/ExpiredJWTCard.spec.tsx.snap
- ui/components/app/Analysis/index.tsx
- Added the Expired JWT Card
- Snapshot testing with dummy data
- Component renders in-browser with `npm run dev`
- Snapshot test was added for this component
> Feature: Expired JWT Card

- Makefile
- scripts/generate-pipeline-data.sh
> Updated e2e script to wait for collector pod to be ready before sending requests. 
> Confirmed post-deploy script does not send requests until the collector pod is ready to export records.
> Updated e2e dev testing workflow

- ui/components/app/Analysis/core/__snapshots__/index.spec.tsx.snap
- ui/components/app/Analysis/core/index.spec.tsx
- ui/components/app/Analysis/core/index.tsx
- ui/components/app/Analysis/index.tsx
- ui/components/app/Summary/Summary.spec.tsx
- ui/components/app/Summary/__snapshots__/Summary.spec.tsx.snap
- ui/components/app/Summary/index.tsx
- ui/components/app/page-sections/AnalysisSection/index.tsx
- ui/pages/index.tsx
- add loading components for the analyses summary and analysis card
- verified that the new components look correct on the design system page
- observed that the loading state works correctly on the index page
- caused an error and observed that the error message appears correctly
> Add loading skeletons and an error message

- ui/components/atoms/SeverityIcon/index.tsx
- Make `SeverityIcon` take all MUI SVGComponent props and forward them
Snapshot tests unaffected by change
Snapshot tests unaffected by change
> Make SeverityIcon take all MUI SVGComponent props and forward them

- CONTRIBUTING.md
- TESTING.md
- scripts/generate-pipeline-data.sh
1. --platform=linux/amd64 is needed for M1 Macs
2. Add docs for a 5432 port collision
> Fix docs for M1, compensate for existing 5432 service

- ui/components/app/Analysis/__snapshots__/ExpiredJWTCard.spec.tsx.snap
- ui/components/app/Analysis/__snapshots__/PasswordInURLCard.spec.tsx.snap
- ui/components/app/Analysis/__snapshots__/ReusedAuthentication.spec.tsx.snap
- ui/components/app/Analysis/__snapshots__/UseOfBasicAuthCard.spec.tsx.snap
- ui/components/app/Analysis/core/CsvExportButton.tsx
- ui/components/app/Analysis/core/__snapshots__/index.spec.tsx.snap
- ui/components/app/Analysis/core/index.tsx
- ui/components/app/Header/Header.tsx
- ui/components/app/Summary/__snapshots__/Summary.spec.tsx.snap
- ui/components/app/Summary/index.tsx
- ui/components/atoms/SeverityIcon/__snapshots__/SeverityIcon.spec.tsx.snap
- ui/components/atoms/SeverityIcon/index.tsx
- ui/pages/index.tsx
- ui/styles/globals.css
Summary Card updated for medium to large screens, adjusting the layout to fill space as needed. Loading Skeleton also updated to match. Weakness link truncated on smaller screens.
Severity Icon for "Low" updated to a circle down arrow... not sure how i feel about it but it's better than a moon. I tried the a few down arrows and they didn't have the circle around them …
> [STR-4482]: round 2 of style updates

- scripts/generate-pipeline-data.sh
1. Check for kubeshark in PATH in `generate-pipeline-data.sh`
2. Check for kubeshark version in `generate-pipeline-data.sh`
3. Wait for curl pods to be ready in `generate-pipeline-data.sh`
Check out CAST
```sh
cd ~
rm -rf /tmp/str-4510
mkdir -p /tmp/str-4510
cd /tmp/str-4510
ln -s ~/src/cast ./cast
```
Uninstall kubeshark
```sh
rm -f /usr/local/bin/kubeshark
``` …
> Check for kubeshark version, wait for curl pods to be ready

- cmd/castRunner.go
> Fixed typo in kubeshark compatible architecture and os list used for downloading the kubeshark binary. Updated port-forwarding logging to link accurately based on port flag. 
> Ran cast in test mode according to [TESTING.md](https://github.com/corshatech/cast/blob/main/TESTING.md) with results as expected. 
> Confirmed port-forwarding logging now updates with port …
> Updated kubeshark compatible architecture/os list

- CONTRIBUTING.md
- README.md
- TESTING.md
- add details about the helm dependency in the dev workflow
> Add details about requirements

- ui/components/app/Analysis/KubesecCard.tsx
- use serialized JSON as kubesec row ID in order to fix table paging
> Make Kubesec analysis row ID unique

- ui/components/app/Summary/__snapshots__/Summary.spec.tsx.snap
- ui/components/app/Summary/index.tsx
- ui/lib/findings.ts
I updated the function that calculates the total of findings to include the findings in the `data.inRequests` path for 'reused-auth' findings
ensure the numbers in the bottoms of the tables total up to equal the number in the summary card
> fix(STR-4588): update findings total for reused auth

- scripts/generate-pipeline-data.sh
> STR-4640 Allow $CONTEXT to be set externally

- collector/collector.go
- collector/deadline.go
Add read and write deadlines to the ksConnection use
> STR-4636: Set read and write deadlines

- collector/Dockerfile
Fix the collector build: specify the entire collector directory for compile
> bug/STR-4643: Fix the collector build

- .github/workflows/linter.yml
- .markdownlint.yaml
- DEVELOPING.md
- README.md
- TESTING.md
Resolves STR-4614 by adding a workaround to the documentation and testing steps.
> Add warning about M1 + Kubesec

- README.md
- TESTING.md
- Changed install instructions to "install with brew"
N/A - only documentation changed
N/A - only documentation changed
> Advocate installing CAST with Brew

- ui/__tests__/analysis/reused-authentication.test.ts
- ui/__tests__/findings.test.ts
- ui/components/app/Analysis/ExpiredJWTCard.spec.tsx
- ui/components/app/Analysis/PasswordInURLCard.spec.tsx
- ui/components/app/Analysis/ReusedAuthenticationCard.spec.tsx
- ui/components/app/Analysis/UseOfBasicAuthCard.spec.tsx
- ui/components/app/Analysis/__snapshots__/PasswordInURLCard.spec.tsx.snap
- ui/components/app/Analysis/core/index.tsx
- ui/components/app/page-sections/AnalysisSection/index.tsx
- ui/lib/analysis/reused-authentication.ts
- Added new weakness classification for Reused Auth to point to OWASP's [Broken Authentication Risk](https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/)
- Updated title and description to match the OWASP Risk
- Changed `weaknessLink`'s style in the table to prevent the reportedAt column from shrinking 
- Checked that new description displayed …
> [CAST-157] Classify Reused Auth

- ui/__tests__/analysis/pass_in_url.test.ts
- ui/lib/analysis/pass_in_url.ts
- Updated weakness classification for Password In URL to point to OWASP's [Broken Authentication Risk](https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/)
- Updated title and description to match the OWASP Risk
- Checked that new description displayed properly
- Updated unit tests to use new description, title, weaknessLink and weaknessTitle
> [CAST-156] Reclassify Password In URL

- ui/__tests__/analysis/expired-jwt.test.ts
- ui/lib/analysis/expired-jwt.ts
- Added new weakness classification for Expired JWT to point to OWASP's [Broken Authentication Risk](https://owasp.org/API-Security/editions/2023/en/0xa2-broken-authentication/)
- Updated title and description to match the OWASP Risk
- Checked that new description displayed properly
- Updated unit tests to use new description, title, weaknessLink and weaknessTitle
- …
> [CAST-155] Classify Expired JWT

- k8s/helm/cast/files/init.sql
- scripts/generate-pipeline-data.sh
- ui/components/app/Analysis/RequestTooSlowCard.spec.tsx
- ui/components/app/Analysis/RequestTooSlowCard.tsx
- ui/components/app/Analysis/__snapshots__/RequestTooSlowCard.spec.tsx.snap
- ui/components/app/Analysis/index.tsx
- ui/lib/analysis/request_too_slow.ts
- ui/lib/findings.ts
- ui/pages/api/analyses.ts
- ui/pages/index.tsx
- ui/styles/globals.css
- Added Request Too Slow data generation to the `generate-pipeline-data.sh` script
- Created RequestTooSlowCard that populates a table with data from long-running requests
- Created request-too-slow endpoint that finds traffic data which is not a websocket or SSE and whose `elapsedTime` returned from kubeshark is longer than sixty seconds
- Fixed postgres indexes
- …
> [CAST-158] Implement Request Too Slow Detection

- ui/components/app/Analysis/KubesecCard.spec.tsx
- ui/components/app/Analysis/KubesecCard.tsx
- ui/components/app/Analysis/__snapshots__/KubesecCard.spec.tsx.snap
- ui/components/app/Analysis/index.tsx
- ui/lib/analysis/kubesec-resources.ts
- ui/lib/analysis/kubesec-types.ts
- ui/lib/analysis/kubesec.ts
- ui/pages/api/analyses.ts
- Duplicated KubesecFinding into KubesecResourcesFinding
- Created kubesec-resources analysis to look for Rule IDs relating to resource requests/limits
- Removed resource related findings from combined Kubesec table
- Deployed and checked that Rules with IDs `RequestsMemory`, `RequestsCPU`, `LimitsMemory`, `LimitsCPU` or `VolumeClaimRequestsStorage` appear in the new …
> [CAST-154] Kubesec OWASP Unrestricted Resource Consumption

- .vscode/settings.json
- ui/lib/internal/index.ts
- ui/lib/metadata.ts
- ui/package-lock.json
- ui/package.json
- ui/pages/api/upload/feodo-data.ts
- Created file upload route for FEODO Banlist data .json
- A test page was constructed that exercises the functionality using an HTML form.
- Manual testing using the test page succeeded.
- N/A - functionality is 100% database glue. Data types/validation statically checked with `zod`
> CAST-213: Feodo data upload route

- k8s/helm/cast/files/init.sql
- ui/pages/api/upload/feodo-data.ts
- Fixed issue discovered during QA, where the extra large FEODO dataset can contain duplicate IP addresses.
> Large FEODO dataset can contain duplicate ipaddr

- k8s/helm/cast/files/init.sql
- scripts/generate-pipeline-data.sh
Follow up to #102 to specify that the traffic IP view should be materialized.
**`k8s/helm/cast/files/init.sql`**:
- Materialize the view.
**`scripts/generate-pipeline-data.sh`**:
- Modify one test request to use both `X-Forwarded-For` and `X-Real-Ip` headers in the same request.
1. Set up your local development environment following these instructions: https://github.com/corshatech/cast/blob/main/DEVELOPING.md.
2. Make sure that the …
> CAST-204: Materialize the "mat" view

- ui/pages/api/matview-refresh.ts
- Added `/api/matview-refresh` route for dev testing to populate the materialized view that captures traffic IP information
- Deployed CAST locally, navigated to localhost:3000/api/matview-refresh and checked that clicking the button populates the `matview_traffic_ips` view in postgres
N/A
> [CAST-244] Create Matview Refresh Endpoint

- Makefile
- k8s/helm/cast/files/init.sql
- k8s/helm/cast/templates/secrets.yaml
- k8s/helm/cast/values.yaml
- ui/pages/api/enablements.ts
- ui/pages/api/upload/geo-location-data.ts
- ui/pages/index.tsx
- Added make target to validate helm configuration
- Added geolocation to init.sql using [Maxmind's documentation](https://dev.maxmind.com/geoip/importing-databases/postgresql)
- Created secret to store script that will enable the PostGIS extension in the bitnami PostgreSQL instance
- Updated enablements route to include a check for geo location data
- Duplicated …
> [CAST-208] Geo Location Data Upload

- DEVELOPING.md
- Updated `DEVELOPING.md`
- Deployment instructions up-to-date as of time of writing.
- Explicitly linked download locations and exact versions of tooling required to reconstruct dev env
- Documented known-issues as of time of writing
- Added note about `KUBECONFIG` known issue
- Added note about `--context` known issue
N/A - Documentation updates
N/A - Documentation …
> Fully up-to-date DEVELOPING.md

- collector/analysis/url_regex/url_regex.go
- scripts/generate-pipeline-data.sh
- Added detections using the new regex engine for vulnerabilities that could be found in the URL
- [Server Side Request Forgery](https://owasp.org/API-Security/editions/2023/en/0xa7-server-side-request-forgery/)
- [SQL Injection](https://owasp.org/Top10/A03_2021-Injection/)
- [Log4Shell](https://nvd.nist.gov/vuln/detail/CVE-2021-44228)
- …
> [CAST-153] Implement URL Regexes

- .github/workflows/linter.yml
- ui/components/app/Analysis/ReusedAuthenticationCard.tsx
- Added Alert component when traffic rows don't match count from reused secret rows in ReusedAuthenticationCard
- Removed useSWR call to simulate timing being out of sync for frontend and saw that Alert was displayed
N/A
> [CAST-270] Display Alert for Count Mismatch

- go.work
- plugins/jenkins/auth.go
- plugins/jenkins/auth_test.go
- plugins/jenkins/connection.go
- plugins/jenkins/go.mod
- plugins/jenkins/go.sum
- plugins/jenkins/main.go
- plugins/jenkins/user.go
**`go.work`, `plugins/jenkins/go.mod`, `plugins/jenkins/go.sum`**:
- Initialize go dependency management for Jenkins plugin package.
**`plugins/jenkins/main.go`**:
- Pull out request building logic into helper function.
- Tweak `main()` logic slightly to now:
- Build the request URL
- Create a new connection based on that URL
- Execute the users query using that connection
- Log helpful info throughout
**`plugins/jenkins/auth.go`**:
- …
> CAST-197: Prepare Jenkins plugin package for querying users on demand

- plugins/jenkins/auth.go
- plugins/jenkins/auth_test.go
**`plugins/jenkins/auth.go`**:
- Auth strategy methods to read values from environment variables now return auth strategy (or nil) directly.
**`plugins/jenkins/auth_test.go`**:
-  Update tests for tweaked method signatures.
Unit tests all pass:
```
cast % go test ./plugins/jenkins/...
ok  	github.com/corshatech/cast/plugins/jenkins	0.109s
```
I also tested the Jenkins plugin manually:
1. I signed into our Jenkins instance and hit this …
> CAST-197: Clean up auth strategy construction for Jenkins plugin
